[theme]
base = "light"
primaryColor = "#078d83"
backgroundColor = "#f4f8f9"
secondaryBackgroundColor = "#ffffff"
textColor = "#09283b"
font = "sans serif"

[server]
maxUploadSize = 50
enableXsrfProtection = true

[browser]
gatherUsageStats = false
